---
version: "3.8"
services:
  movies:
    image: saikrishnass/netflixmovies:latest
    ports:
      - 91:80
    deploy:
      replicas: 3
  train:
    image: saikrishnass/netflixtrain:latest
    ports:
      - 92:80
    deploy:
      replicas: 3
  recharge:
    image: saikrishnass/netflixrecharge:latest
    ports:
      - 93:80
    deploy:
      replicas: 3
  dth:
    image: saikrishnass/netflixdth:latest
    ports:
      - 94:80
    deploy:
      replicas: 3
