---
version: "3.8"
services:
  movies:
    image: saikrishnass/netflixmovies:latest
    ports:
      - 81:80
    deploy:
      replicas: 3
  train:
    image: saikrishnass/netflixtrain:latest
    ports:
      - 82:80
    deploy:
      replicas: 3
  recharge:
    image: saikrishnass/netflixrecharge:latest
    ports:
      - 83:80
    deploy:
      replicas: 3
  dth:
    image: saikrishnass/netflixdth:latest
    ports:
      - 84:80
    deploy:
      replicas: 3
